### ISSUE TITLE
How to add CRF layer after biLSTM output layer?

### ISSUE THREAD

**Issue by SJinping** [ne7ermore/torch_light#2]
It seems that in biLSTM-CRF model only biLSTM is  trained without a CRF layer added to the output layer of biLSTM. CRF is only called after the probability of each tag for each word is predicted by loading a trained biLSTM model (in `predict.py`). So, the CRF only works in predicting stage rather than in training stage?

**Comment by Elliot-Chan** [comment]
https://github.com/catnlp/PyTorchSeqLabel
This repository may help you.

**Comment by ne7ermore** [comment]
So, the CRF only works in predicting stage rather than in training stage?
-----------
Not only predicting but training

training stage: https://github.com/ne7ermore/torch_light/blob/master/LSTM-CNNs-CRF/model.py#L190=
treat crf layer as a Matrix, updating it`s weights in training  

predicting stage: https://github.com/ne7ermore/torch_light/blob/master/LSTM-CNNs-CRF/model.py#L74

Understanding HHM, CRF and viterbi may help you how to implement this model :)
